### ISSUE TITLE
Exkeymo doesn't work on Android 11.

### ISSUE THREAD

**Issue by gety9** [ris58h/custom-keyboard-layout#1]
Does exkeymo.herokuapp support Android 11?

I followed instructions:
1 created simple test layout
```
type OVERLAY

map key 44 a

```
(remapping z to a, confirmed with gamepad tester that z has code = 44)
2 downloaded and installed the app
3 enabled "Custom" on physical keyboard.

Still pressing z types z.

What can be the reason?

**Comment by gety9** [comment]
UPDATE:
using keyboard_layout_en_us.kcm sample and filling form/downloading app on android tablet (iceraven browser) worked.

No sure where the problem was, what didn't work:
- using simple test layout and submitting form/downloading app on android (einkbro browser) resulted in error parsing the package unable to install app)
- using simple test layout and submitting form/downloading app on Windows FF and Chrome resulted in installable app, but "Custom" layout didn't bring any visible results.

So either my minimal test layout was not good or OS/browser you submit form / download app matters.

**Comment by ris58h** [comment]
Sorry for late response. Github hasn't notified me about the issue.
Is it the issue with https://exkeymo.herokuapp.com/ ?
If so, it has a separate project https://github.com/ris58h/exkeymo-web
