### ISSUE TITLE
Request: Complied apk

### ISSUE THREAD

**Issue by EstebanOD** [ris58h/custom-keyboard-layout#2]
Hello!
I would like to start by thanking you for the website: https://exkeymo.herokuapp.com/
I've spent the past 7 hours on it, really practical, I couldn't find any application that would truely let me create my own keyboard before finding your website.

However, I am on an android tablet, so I don't think I can complie it myself; I would like to ask you, if it's possible and if you have the time to do it, to provide an apk for the Custom Keyboard Layout. I would really appreciate it, if it's not possible then it's okay too, thank you.

**Comment by ris58h** [comment]
Hi! Thank you.

As stated in README `It's a skeleton, so there is no apk or Play Store link`.
What do you want to do if https://exkeymo.herokuapp.com/ is not enough for your needs?

**Comment by EstebanOD** [comment]
I was just asking because there's more layouts

**Comment by ris58h** [comment]
How many layouts do you need? ExKeyMo supports up to two.
If you need more than two layouts you could send the layouts to me so I could compile the APK. Just test them one by one before sending so you can be sure that they work properly.

**Comment by pseudoparenchymatous** [comment]
Hello, I'm a student programmer but I haven't worked with APKs yet. Can you help with steps on compiling an APK from this repo?  Thank you.

**Comment by ris58h** [comment]
@pseudoparenchymatous hi.
This is just a simple Android project and doesn't require anything special to build. 
You could look at official guides:
https://developer.android.com/training/basics/firstapp
https://developer.android.com/codelabs/build-your-first-android-app#0
